# Generated by Django 5.2 on 2025-06-17 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0003_task_categorie_task_team_alter_task_created_at_and_more'),
        ('teams', '0003_team_is_ocupied'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TaskTeam', to='tasks.task', verbose_name='Tarefa')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TeamTask', to='teams.team', verbose_name='Equipe')),
            ],
            options={
                'verbose_name': 'Equipe Tarefa',
                'verbose_name_plural': 'Equipes Tarefas',
            },
        ),
    ]
