# Generated by Django 5.2 on 2025-08-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtask',
            name='begin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início da execução'),
        ),
        migrations.AddField(
            model_name='teamtask',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim da execução'),
        ),
    ]
