# Generated by Django 5.2 on 2025-08-13 23:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_team'),
        ('team_task', '0002_teamtask_begin_teamtask_end'),
        ('teams', '0003_team_is_ocupied'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamtask',
            options={},
        ),
        migrations.AddField(
            model_name='teamtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='begin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tasks', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tasks', to='teams.team'),
        ),
        migrations.AlterUniqueTogether(
            name='teamtask',
            unique_together={('team', 'task')},
        ),
        migrations.AlterModelTable(
            name='teamtask',
            table='team_task',
        ),
    ]
