# Generated by Django 5.2 on 2025-08-14 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_team'),
        ('team_task', '0003_alter_teamtask_options_teamtask_created_at_and_more'),
        ('teams', '0003_team_is_ocupied'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamtask',
            options={'verbose_name': 'Equipe Tarefa', 'verbose_name_plural': 'Equipes Tarefas'},
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='begin',
            field=models.DateTimeField(verbose_name='Início da execução'),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='end',
            field=models.DateTimeField(verbose_name='Fim da execução'),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tasks', to='tasks.task', verbose_name='Tarefa'),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tasks', to='teams.team', verbose_name='Equipe'),
        ),
    ]
