# Generated by Django 5.2 on 2025-07-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(default=1, max_length=100, unique=True, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='password',
            field=models.CharField(default=1, max_length=64, verbose_name='Senha'),
            preserve_default=False,
        ),
    ]
