# Generated by Django 5.2 on 2025-06-17 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timespan', models.IntegerField(default=24, verbose_name='Período máximo para agendamento')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome equipamento')),
                ('is_ocupied', models.BooleanField(default=False, verbose_name='Está ocupado')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='DowntimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EquipmentDownTime', to='equipment.equipment', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Período de inatividade',
                'verbose_name_plural': 'Períodos de inatividade',
            },
        ),
    ]
