# Generated by Django 5.2 on 2025-06-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_timespan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='timespan',
        ),
    ]
