# Generated by Django 5.2 on 2025-05-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='begin',
            field=models.DateField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AddField(
            model_name='operation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='operation',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AddField(
            model_name='operation',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
    ]
