# Generated by Django 5.2 on 2025-06-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_operation_begin_operation_created_at_operation_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='begin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início'),
        ),
    ]
