# Generated by Django 5.2 on 2025-06-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_operation_begin'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='finalized',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
        migrations.AddField(
            model_name='operation',
            name='timespan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo total de conslusão'),
        ),
    ]
