# Generated by Django 5.2 on 2025-07-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_operation_finalized_operation_timespan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='end',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='timespan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo total de conclusão'),
        ),
    ]
