# Generated by Django 5.2 on 2025-08-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_operation_end_alter_operation_timespan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim'),
        ),
    ]
