# Generated by Django 5.2 on 2025-06-18 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0002_operation_begin_operation_created_at_operation_end_and_more'),
        ('tasks', '0004_remove_task_updated_at_task_finished_at_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Operations', to='operations.operation', verbose_name='Operação')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Tasks', to='tasks.task', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
            },
        ),
    ]
