# Generated by Django 5.2 on 2025-06-18 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_task', '0001_initial'),
        ('operations', '0002_operation_begin_operation_created_at_operation_end_and_more'),
        ('tasks', '0004_remove_task_updated_at_task_finished_at_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtask',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Operations', to='operations.operation', verbose_name='Operação'),
        ),
        migrations.AlterField(
            model_name='operationtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tasks', to='tasks.task', verbose_name='Tarefa'),
        ),
    ]
