# Generated by Django 5.2 on 2025-06-21 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_task', '0002_alter_operationtask_operation_and_more'),
        ('operations', '0004_operation_finalized_operation_timespan'),
        ('tasks', '0004_remove_task_updated_at_task_finished_at_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtask',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Operations', to='operations.operation', verbose_name='Operação'),
        ),
        migrations.AlterField(
            model_name='operationtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tasks', to='tasks.task', verbose_name='Tarefa'),
        ),
    ]
