# Generated by Django 5.2 on 2025-07-02 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_task', '0003_alter_operationtask_operation_and_more'),
        ('operations', '0005_alter_operation_end_alter_operation_timespan'),
        ('tasks', '0006_alter_task_options_alter_task_finished_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationtask',
            options={'verbose_name': 'Associação Operação-Tarefa', 'verbose_name_plural': 'Associações Operação-Tarefa'},
        ),
        migrations.AlterField(
            model_name='operationtask',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_tasks', to='operations.operation', verbose_name='Operação'),
        ),
        migrations.AlterField(
            model_name='operationtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_tasks', to='tasks.task', verbose_name='Tarefa'),
        ),
    ]
