# Generated by Django 5.2 on 2025-05-07 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_tasks', '0001_initial'),
        ('operations', '0002_operation_begin_operation_created_at_operation_end_and_more'),
        ('tasks', '0002_task_created_at_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtasks',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Operations', to='operations.operation', verbose_name='Operação'),
        ),
        migrations.AddField(
            model_name='operationtasks',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Tasks', to='tasks.task', verbose_name='Tarefa'),
        ),
    ]
