# Generated by Django 5.2 on 2025-05-07 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categorie_description'),
        ('tasks', '0002_task_created_at_task_updated_at'),
        ('teams', '0002_team_name_team_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Categories', to='categories.categorie', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Teams', to='teams.team', verbose_name='Equipe'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Atualizado em'),
        ),
    ]
