# Generated by Django 5.2 on 2025-06-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_categorie_task_team_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='task',
            name='finished_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Finalizado em'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('finished', 'Finalizada')], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
