# Generated by Django 5.2 on 2025-06-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_updated_at_task_finished_at_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='categorie',
            new_name='category',
        ),
    ]
