# Generated by Django 5.2 on 2025-07-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_categorie_task_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AlterField(
            model_name='task',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em'),
        ),
    ]
