# Generated by Django 5.2 on 2025-08-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_options_alter_task_finished_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team',
        ),
    ]
