# Generated by Django 5.2 on 2025-09-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='on_mount',
            field=models.BooleanField(default=False, verbose_name='Em montagem'),
        ),
    ]
