# Generated by Django 5.2 on 2025-05-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='description',
            field=models.CharField(default=1, max_length=60, unique=True, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
