# Generated by Django 5.2 on 2025-06-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categorie_description'),
        ('tasks', '0005_rename_categorie_task_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
