# Generated by Django 5.2 on 2025-06-21 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0003_remove_equipment_timespan'),
        ('operations', '0004_operation_finalized_operation_timespan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_operations', to='equipment.equipment', verbose_name='Equipamento')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_equipments', to='operations.operation', verbose_name='Operação')),
            ],
            options={
                'verbose_name': 'Equipamento da Operação',
                'verbose_name_plural': 'Equipamentos das Operações',
            },
        ),
    ]
