# Generated by Django 5.2 on 2025-08-12 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0006_alter_operation_end'),
        ('teams', '0003_team_is_ocupied'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(blank=True, null=True, verbose_name='Início da execução')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Fim da execução')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OperationTeam', to='operations.operation', verbose_name='Operação')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TeamOperation', to='teams.team', verbose_name='Equipe')),
            ],
            options={
                'verbose_name': 'Equipe Operação',
                'verbose_name_plural': 'Equipes Operações',
            },
        ),
    ]
