# Generated by Django 5.2 on 2025-06-17 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('tasks', '0003_task_categorie_task_team_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EquipmentTask', to='equipment.equipment', verbose_name='Equipamento')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Task', to='tasks.task', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'equipamento_tarefa',
                'verbose_name_plural': 'equipamentos_tarefas',
            },
        ),
    ]
