# Generated by Django 5.2 on 2025-06-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_name_team_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_ocupied',
            field=models.BooleanField(default=False, verbose_name='Está ocupado'),
        ),
    ]
