# Generated by Django 5.2 on 2025-09-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_is_ocupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='on_mount',
            field=models.BooleanField(default=False, verbose_name='Em montagem'),
        ),
    ]
